Attempt to debug workflow status getting

diff --git a/.github/workflows/publish_output.yml b/.github/workflows/publish_output.yml
--- a/.github/workflows/publish_output.yml
+++ b/.github/workflows/publish_output.yml
@@ -9,14 +9,26 @@ jobs:
     runs-on: ubuntu-latest
 #    if: ${{ github.event.workflow_run.conclusion == 'success' }}
     steps:
-    - name: Get workflow id
+    - name: Get own workflow id
       shell: bash
       run: |
-        WORKFLOW_ID=$(curl --header 'authorization: Bearer ${{ inputs.github_token }}' \
+        RESPONSE=$(curl --header 'authorization: Bearer ${{ inputs.github_token }}' \
                            --header 'content-type: application/json' \
-        https://api.github.com/repos/${{ github.repository }}/actions/runs/1794769003 | jq -r .workflow_id)
+        https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }})
+        echo "RESPONSE=$RESPONSE"
+        OWN_WORKFLOW_ID=$(echo $RESPONSE | jq -r .workflow_id)
+        echo "Own Workflow id: ${OWN_WORKFLOW_ID}"
+    - name: Get testing workflow id
+      shell: bash
+      run: |
+        RESPONSE=$(curl --header 'authorization: Bearer ${{ inputs.github_token }}' \
+                           --header 'content-type: application/json' \
+        https://api.github.com/repos/${{ github.repository }}/actions/runs/1794769003)
+        echo "RESPONSE=$RESPONSE"
+        WORKFLOW_ID=$(echo $RESPONSE | jq -r .workflow_id)
         echo "WORKFLOW_ID=$WORKFLOW_ID" >> $GITHUB_ENV
         echo "Workflow id: ${WORKFLOW_ID}"
+        [[ "${WORKFLOW_ID}" -ne "null" ]] && echo "Could not get workflow ID" && exit 1
     - name: Get previous build status
       shell: bash
       id: last_status
