Fix usage of GH token in workflow

diff --git a/.github/workflows/publish_output.yml b/.github/workflows/publish_output.yml
--- a/.github/workflows/publish_output.yml
+++ b/.github/workflows/publish_output.yml
@@ -13,7 +13,7 @@ jobs:
     - name: Get own workflow id
       shell: bash
       run: |
-        RESPONSE=$(curl --header 'authorization: Bearer ${{ inputs.github_token }}' \
+        RESPONSE=$(curl --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
                            --header 'content-type: application/json' \
         https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }})
         echo "RESPONSE=$RESPONSE"
@@ -22,19 +22,19 @@ jobs:
     - name: Get testing workflow id
       shell: bash
       run: |
-        RESPONSE=$(curl --header 'authorization: Bearer ${{ inputs.github_token }}' \
+        RESPONSE=$(curl --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
                            --header 'content-type: application/json' \
         https://api.github.com/repos/${{ github.repository }}/actions/runs/1794769003)
         echo "RESPONSE=$RESPONSE"
         WORKFLOW_ID=$(echo $RESPONSE | jq -r .workflow_id)
         echo "WORKFLOW_ID=$WORKFLOW_ID" >> $GITHUB_ENV
         echo "Workflow id: ${WORKFLOW_ID}"
-        [[ "${WORKFLOW_ID}" -ne "null" ]] && echo "Could not get workflow ID" && exit 1
+        [[ "${WORKFLOW_ID}" -eq "null" ]] && echo "Could not get workflow ID" && exit 1
     - name: Get previous build status
       shell: bash
       id: last_status
       run: |
-        last_status=$(curl --silent --header 'authorization: Bearer ${{ inputs.github_token }}' \
+        last_status=$(curl --silent --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
                                     --header 'content-type: application/json' \
         "https://api.github.com/repos/${{ github.repository }}/actions/workflows/${{ env.WORKFLOW_ID }}/runs?per_page=1&status=completed&branch=${{ env.BRANCH_NAME }}" \
         | jq -r .workflow_runs[0].conclusion)
