Fix publish output workflow

diff --git a/.github/workflows/publish_output.yml b/.github/workflows/publish_output.yml
--- a/.github/workflows/publish_output.yml
+++ b/.github/workflows/publish_output.yml
@@ -10,15 +10,6 @@ jobs:
     runs-on: ubuntu-latest
 #    if: ${{ github.event.workflow_run.conclusion == 'success' }}
     steps:
-    - name: Get own workflow id
-      shell: bash
-      run: |
-        RESPONSE=$(curl --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
-                           --header 'content-type: application/json' \
-        https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }})
-        echo "RESPONSE=$RESPONSE"
-        OWN_WORKFLOW_ID=$(echo $RESPONSE | jq -r .workflow_id)
-        echo "Own Workflow id: ${OWN_WORKFLOW_ID}"
     - name: Get testing workflow id
       shell: bash
       run: |
@@ -29,8 +20,8 @@ jobs:
         WORKFLOW_ID=$(echo $RESPONSE | jq -r .workflow_id)
         echo "WORKFLOW_ID=$WORKFLOW_ID" >> $GITHUB_ENV
         echo "Workflow id: ${WORKFLOW_ID}"
-        [[ "${WORKFLOW_ID}" -eq "null" ]] && echo "Could not get workflow ID" && exit 1
-    - name: Get previous build status
+        if [[ "${WORKFLOW_ID}" -eq "null" ]] ; then echo "Could not get workflow ID"; exit 1 ; fi
+    - name: Get previous testing status
       shell: bash
       id: last_status
       run: |
@@ -44,7 +35,7 @@ jobs:
       shell: bash
       id: check_status
       run: |
-        [[ "${LAST_STATUS}" -ne "success" ]] && exit 1
+        if [[ "${LAST_STATUS}" -ne "success" ]] ; then echo "Last test status was not success: '${LAST_STATUS}'" ; exit 1 ; fi
     - uses: actions/checkout@v2
       with:
         ref: main
